### ISSUE TITLE
nuskybgd_image can't find aperbgd[A/B]_det[0-3].pha files in nuskybgd/auxil/*

### ISSUE THREAD

**Issue by zzzhty** [NuSTAR/nuskybgd#20]
Everything goes well before I tried to use "nuskybgd_image" producing simulated background, the program broke and warned me that "Specified FITS file not found: ~/PATH-to-nuskybgd/nuskybgd/auxil/aperbgdA_det0.pha", but there doesn't exist any "aper*" files in the "auxil" folder. Besides, "fcxbbgd" and "grxe" files don't exist.

That quite confuses me, is there anything important I missed?

**Comment by bwgref** [comment]
Did you run the following IDL scripts?

nuskybgd_instrmap,dir,obsid,'A','bgd'
nuskybgd_instrmap,dir,obsid,'B','bgd'

**Comment by zzzhty** [comment]
Yes, I did.

Actually I have asked Wik for help yesterday and found the issue occurred because I didn't run the "nuskybgd_imrefspec.pro".

Now the problem is solved, thanks for all your assistance!
